### ISSUE TITLE
WebSocket Crash

### ISSUE THREAD

**Issue by VisionMise** [dcodeIO/RustWeb#2]
Web socket fatal error when server running for so long.

Also, Oxide could handle the below error gracefully, if within your initialization code, you were unbinding any URI prefixes. Like http://*:25015, unbinding that first, would allow server admins to at least execute a reload without restarting the server by: 'oxide.reload rustweb'

```
1/25/2015 7:20:44 PM|Fatal|WebSocket.processException|WebSocketSharp.WebSocketEx
ception: The header part of a frame cannot be read from the data source.
                             at WebSocketSharp.WebSocketFrame+<>c__DisplayClass7
.<ReadAsync>b__6 (System.Byte[] header) [0x00000] in <filename unknown>:0 s out
                             at WebSocketSharp.Ext+<>c__DisplayClass6.<ReadBytes
Async>b__5 (IAsyncResult ar) [0x00000] in <filename unknown>:0
```

I don't know C#, but i'm going to fork it and take a look and see if I can help you find the issue. I think this is the best plugin on oxide atm!!! great work!

**Comment by dcodeIO** [comment]
RustWeb consists of two parts: An extension and a plugin.

* The extension basically sits on the same level as Oxide itself and you cannot reload it (just like Oxide).
* Only the plugin, which is just the glue code between Oxide and RustWeb, "can" be reloaded.

I can surely harden the plugin for the case that someone tries to reload it, but if you want to update RustWeb, a server restart is inevitable.

**Comment by dcodeIO** [comment]
Are you absolutely sure that the exception above is the cause for the crash? For me it looks like one single websocket connection had an error, not the entire server. Could you paste me some more output of the end of the log files?

**Comment by VisionMise** [comment]
I think you are correct, this socket was the culprit. Sorry it's been a bit since I worked with .NET in any capacity. 

The server continued to serve the website thereafter, but without any monuments, buildings, or player data getting updated. The json files were sill intact, just reflecting the latest data, not the current data. 

I don't have the logs, but can replicate it again in about an hours time and then paste them in. I also noticed this when loading: (Which I think may be from a command with the same name already being bound). When unloading all other plugins, The initialization error does not occur. I haven't figured out which plugin it is yet.

[1/25/2015 5:16:52 PM] [Oxide] 5:16 PM [Info] Initializing
[1/25/2015 5:16:52 PM] [Oxide] 5:16 PM [Info] Initializing
[1/25/2015 5:16:52 PM] [Oxide] 5:16 PM [Debug]   at System.Collections.Generic.Dictionary`2[System.String,ConsoleSystem+Command].Add (System.String key, .Command value) [0x00000] in <filename unknown>:0 
  at Oxide.Rust.Libraries.Command.AddConsoleCommand (System.String name, Oxide.Core.Plugins.Plugin plugin, System.String callbackname) [0x00000] in <filename unknown>:0 
  at Oxide.Rust.Plugins.RustWebPlugin.Init () [0x00000] in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
[1/25/2015 5:17:03 PM] Creating Terrain..
[1/25/2015 5:17:03 PM] Generating terrain of size 4000 with seed 954993156

**Comment by VisionMise** [comment]
I cannot see any updates to any of my log files, which maybe a separate issue, however I am able to get this from the console; which is incomplete. Due to the wrapping and such it's somewhat mangled.

I opened my map up to the internet here if it helps
http://kuhlonline.com:25015/

'
1/25/2015 9:36:52 PM|Error|WebSocket.SendAsync|While closing the WebSocket conne
ction.
1/25/2015 9:36:52 PM|Error|WebSocket.SendAsync|While closing the WebSocket conne
1/25/2015 9:36:53 PM|Fatal|WebSocket.processException|WebSocketSharp.WebSocketEx
ception: The header part of a frame cannot be read from the data source.
                             at WebSocketSharp.WebSocketFrame+<>c__DisplayClass7
.<ReadAsync>b__6 (System.Byte[] header) [0x00000] in <filename unknown>:0 s out
                             at WebSocketSharp.Ext+<>c__DisplayClass6.<ReadBytes
'

**Comment by dcodeIO** [comment]
Related: http://forum.rustoxide.com/threads/rustweb.6385/page-11#post-62320
