### ISSUE TITLE
RustWeb Dutch translation.

### ISSUE THREAD

**Issue by No4h-** [dcodeIO/RustWeb#6]
{
	"name": "Dutch",
	"author": "No4h",
	"translations": {

		"Procedural Map": "Procedurele Kaart",
		"Worldsize {WORLDSIZE}, Seed {SEED}": "Wereld Grootte {WORLDSIZE}, Wereld Algoritme’ {SEED}",
		"{NUM} / {MAX} players": "{NUM} / {MAX} Spelers",
		"{NUM} sleepers": "{NUM} Slapers",
		"Sign out": "Uitloggen",
		"Open console": "Console openen",
		"Display:": "Weergeven:",
		"Landmarks": "Oriëntatiepunten",
		"Mortality": "Sterfte",
		"Buildings": "Gebouwen",
		"Grid": "Raster",
		"Filter by name...": "Filter op naam ...",

		"Wolf Monument": "Wolf Monument",
		"Lighthouse": "Vuurtoren",
		"Satellite Dish": "Satelietschotel",
		"Cave": "Grot",
		"Radtown": "Radtown",

		"Allies": "Bondgenoten",
		"Recent players": "Recente spelers",
		"Who shares their location?": "Wie deelt zijn locatie?",
		"You": "Jij",
		"They": "Zij",
		"Mutually": "Wederzijds",

		"Do you really want to SHARE your location with \"{NAME}\"?": "Wil je echt je locatie DELEN met \"{NAME}\"?",
		"Do you really want to NO LONGER SHARE your location with \"{NAME}\"?": "Wil je echt NIET LANGER UW LOCATIE DELEN met \"{NAME}\"?",
		"Do you really want to MUTUALLY DELETE your connection to \"{NAME}\"?": "Wil je echt uw verbinding met \"{NAME}\" WEDERZIJDS VERWIJDEREN?",
		"Sorry, your browser does not support WebSockets. Please consider an upgrade to use RustWeb!": "Sorry, uw browser ondersteunt geen WebSockets. Overweeg een upgrade om RustWeb alsnog te kunnen gebruiken!",

		"{YOU} just signed in": "{YOU} bent aangemeld",
		"{YOU} now share your location with {NAME}": "{YOU} deelt nu uw locatie met {NAME}",
		"{YOU} no longer share your location with {NAME}": "{YOU} deelt niet langer uw locatie met {NAME}",
		"{NAME} now shares their location with you": "{NAME} deelt nu zijn locatie met u",
		"{NAME} no longer shares their location with you": "{NAME} deelt niet langer zijn locatie met u",
		"{NAME} just woke up": "{NAME} ontwaakte net",
		"{NAME} fell asleep": "{NAME} viel in slaap",
		"{NAME} says:": "{NAME} zegt:",
		"{NAME} spawned in the middle of nowhere": "{NAME} ontwaakte in de middle of nowhere",

		"{NAME} starved to death": "{NAME} stierf van de honger",
		"{NAME} died of dehydration": "{NAME} stierf aan uitdroging",
		"{NAME} froze to death": "{NAME} is doodgevroren",
		"{NAME} drowned": "{NAME} is verdronken",
		"{NAME} burned to death": "{NAME} is levend verbrand",
		"{NAME} bled to death": "{NAME} is doodgebloed",
		"{NAME} died of intoxication": "{NAME} stierf aan vergiftiging",
		"{NAME} committed suicide": "{NAME} pleegde zelfmoord",
		"{NAME} was shot": "{NAME} werd neergeschoten",
		"{NAME} was slashed": "{NAME} werd doorgesneden",
		"{NAME} died of a blunt trauma": "{NAME} stierf aan een zwaar trauma",
		"{NAME} fell to death": "{NAME} viel dood",
		"{NAME} died of radiation": "{NAME} stierf aan straling",
		"{NAME} was bitten to death": "{NAME} werd doodgebeten",
		"{NAME} died": "{NAME} is gestorven",

		"This is you!": "Dit ben jij!"
	}
}

**Comment by dcodeIO** [comment]
Thanks, will be included with the next update!
