### ISSUE TITLE
nothing appears on map ?

### ISSUE THREAD

**Issue by PsychoAxeKiller** [dcodeIO/RustWeb#7]
i have got the map working i have restarted server and done map.export 4000 in rcon and it generated a png, i then did map.monuments and then a server.writecfg just encase. but nothing ever appears on he map. http://173.199.72.207:28016/ any ideas?

**Comment by dcodeIO** [comment]
Looks like you have deleted "config.json": http://173.199.72.207:28016/config.json

**Comment by PsychoAxeKiller** [comment]
yep i just reinstalled it completly and its working cheers
